# 第一阶段
FROM golang AS my_build_stage
WORKDIR $GOPATH/src/
ADD . .
ENV GO111MODULE=on
ENV GOPROXY="https://goproxy.io"
RUN go build main.go
# 第二阶段
FROM busybox:glibc
COPY --from=my_build_stage /go/src/main .
COPY --from=my_build_stage /go/src/conf/bootstrap.ini ./conf/bootstrap.ini
# COPY --from=0 hello . 与COPY --from=my_build_stage hello .等效 0表示第一阶段
CMD ["./main"]